task:

  # increase timeout to the maximum limit
  timeout_in: 120m

  install_script: uname -sr && pkg upgrade -y && pkg install -y bison cmake gmp ninja
  test_script: mkdir build && cd build && cmake -G Ninja -DCMAKE_INSTALL_PREFIX=install .. && cmake --build . && python ../tests/integration-tests.py --verbose && cmake --build . -- install

  matrix:
    - name: FreeBSD 11.2
      freebsd_instance:
        image: freebsd-11-2-release-amd64
    - name: FreeBSD 11.3
      freebsd_instance:
        image: freebsd-11-3-stable-amd64-v20190808
    - name: FreeBSD 12.0
      freebsd_instance:
        image: freebsd-12-0-release-amd64
