task:

  # only test the master branch and pull requests
  only_if: $CIRRUS_BRANCH == "master" || $CIRRUS_PR != ""

  # increase timeout to the maximum limit
  timeout_in: 120m

  install_script: pkg upgrade -y && pkg install -y bash bison cmake gmp libxml2 z3

  # we limit the test suite to a single thread because the Cirrus CI VMs claim
  # to have 2 CPUs but do not seem to give two concurrent processes enough CPU
  # time and we end up having some of the SMT tests time out
  test_script: uname -sr && python3 --version && mkdir build && cd build && cmake .. && cmake --build . && sudo cmake --build . -- install && ../tests/run-tests.py --jobs 1

  matrix:
    - name: FreeBSD 13.0
      freebsd_instance:
        image_family: freebsd-13-0-snap
    - name: FreeBSD 12.1
      freebsd_instance:
        image_family: freebsd-12-1-snap
    - name: FreeBSD 11.3
      freebsd_instance:
        image_family: freebsd-11-3-snap
