task:

  # increase timeout to the maximum limit
  timeout_in: 120m

  matrix:

    - name: Linux, GCC 4.9
      container:
        image: gcc:5.5
      environment:
        DDEBIAN_FRONTEND: noninteractive
        PATH: /opt/cmake-3.21.0-rc3-linux-x86_64/bin:${PATH}
      install_script: apt-get update -y && apt-get install --no-install-recommends -y python3 && wget https://github.com/Kitware/CMake/releases/download/v3.21.0-rc3/cmake-3.21.0-rc3-linux-x86_64.tar.gz && mkdir -p /opt && tar xvf --directory /opt cmake-3.21.0-rc3-linux-x86_64.tar.gz


  # we limit the test suite to a single thread because the Cirrus CI VMs claim
  # to have 2 CPUs but do not seem to give two concurrent processes enough CPU
  # time and we end up having some of the SMT tests time out
  test_script: uname -sr && python3 --version && mkdir build && cd build && cmake .. && cmake --build . && sudo cmake --build . -- install && cmake --build . -- check
