task:

  # increase timeout to the maximum limit
  timeout_in: 120m

  matrix:

    - name: Linux, AFL
      container:
        image: gcc:latest
      install_script: apt-get update && env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends bison cmake libfl-dev && echo core | sudo tee /proc/sys/kernel/core_pattern && ./misc/install-afl.sh
      test_script: uname -sr && python3 --version && mkdir build && cd build && env CC=gcc CXX=afl-g++ CXXFLAGS="-g -fsanitize=address,undefined -fno-sanitize-recover=undefined -O3" cmake .. && cmake --build . && cmake --build . -- install && ../misc/afl-wrapper.sh


  # we limit the test suite to a single thread because the Cirrus CI VMs claim
  # to have 2 CPUs but do not seem to give two concurrent processes enough CPU
  # time and we end up having some of the SMT tests time out
  test_script: uname -sr && python3 --version && mkdir build && cd build && cmake .. && cmake --build . && sudo cmake --build . -- install && cmake --build . -- check
