task:

  # increase timeout to the maximum limit
  timeout_in: 120m

  install_script: pkg upgrade -y && pkg install -y bison cmake gmp libxml2 ninja z3
  test_script: uname -sr && python3 --version && mkdir build && cd build && cmake -G Ninja .. && cmake --build . && sudo cmake --build . -- install && ../tests/integration-tests.py --verbose

  matrix:
    - name: FreeBSD 13.0
      freebsd_instance:
        image_family: freebsd-13-0-snap
    - name: FreeBSD 12.0
      freebsd_instance:
        image_family: freebsd-12-0
    - name: FreeBSD 11.3
      freebsd_instance:
        image_family: freebsd-11-3-snap
