task:

  # increase timeout to the maximum limit
  timeout_in: 120m

  matrix:

    - name: Linux, GCC 4.9
      container:
        image: gcc:5.5
      environment:
        DDEBIAN_FRONTEND: noninteractive
      install_script: apt-get update -y && apt-get install --no-install-recommends -y cmake python3


  # we limit the test suite to a single thread because the Cirrus CI VMs claim
  # to have 2 CPUs but do not seem to give two concurrent processes enough CPU
  # time and we end up having some of the SMT tests time out
  test_script: uname -sr && python3 --version && mkdir build && cd build && cmake .. && cmake --build . && sudo cmake --build . -- install && cmake --build . -- check
