language: cpp

branches:
  only:
    - master

matrix:
  include:

  - name: Ubuntu Linux 20.04, GCC multilib (executable, murphi2c, murphi2xml)
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - g++-multilib
          - libc6-dev-i386
          - libfl-dev
          - libxml2-utils
          - valgrind
    env:
      - TEST_ARGS="executable murphi2c murphi2cHeader murphi2xml"
      - MATRIX_EVAL="CC=gcc && CXX=g++"
      - CXXFLAGS="-pedantic -Werror -g -fno-omit-frame-pointer -fsanitize=undefined -fno-sanitize-recover=undefined -fuse-ld=gold"
      - UBSAN_OPTIONS=print_stacktrace=1

  - name: Ubuntu Linux 20.04, GCC multilib (rumur single-threaded)
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - g++-multilib
          - libc6-dev-i386
          - libfl-dev
          - libxml2-utils
          - valgrind
    env:
      - TEST_ARGS="rumurDebugSingleThreaded rumurSingleThreaded"
      - MATRIX_EVAL="CC=gcc && CXX=g++"
      - CXXFLAGS="-pedantic -Werror -g -fno-omit-frame-pointer -fsanitize=undefined -fno-sanitize-recover=undefined -fuse-ld=gold"
      - UBSAN_OPTIONS=print_stacktrace=1

  - name: Ubuntu Linux 20.04, GCC multilib (rumur optimised single-threaded)
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - g++-multilib
          - libc6-dev-i386
          - libfl-dev
          - libxml2-utils
          - valgrind
    env:
      - TEST_ARGS="rumurDebugOptimisedSingleThreaded rumurOptimisedSingleThreaded"
      - MATRIX_EVAL="CC=gcc && CXX=g++"
      - CXXFLAGS="-pedantic -Werror -g -fno-omit-frame-pointer -fsanitize=undefined -fno-sanitize-recover=undefined -fuse-ld=gold"
      - UBSAN_OPTIONS=print_stacktrace=1

  - name: Ubuntu Linux 20.04, GCC multilib (rumur multithreaded)
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - g++-multilib
          - libc6-dev-i386
          - libfl-dev
          - libxml2-utils
          - valgrind
    env:
      - TEST_ARGS="rumurDebugMultithreaded rumurMultithreaded"
      - MATRIX_EVAL="CC=gcc && CXX=g++"
      - CXXFLAGS="-pedantic -Werror -g -fno-omit-frame-pointer -fsanitize=undefined -fno-sanitize-recover=undefined -fuse-ld=gold"
      - UBSAN_OPTIONS=print_stacktrace=1

  - name: Ubuntu Linux 20.04, GCC multilib (rumur optimised multithreaded)
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - g++-multilib
          - libc6-dev-i386
          - libfl-dev
          - libxml2-utils
          - valgrind
    env:
      - TEST_ARGS="rumurDebugOptimisedMultithreaded rumurOptimisedMultithreaded"
      - MATRIX_EVAL="CC=gcc && CXX=g++"
      - CXXFLAGS="-pedantic -Werror -g -fno-omit-frame-pointer -fsanitize=undefined -fno-sanitize-recover=undefined -fuse-ld=gold"
      - UBSAN_OPTIONS=print_stacktrace=1

  - name: Ubuntu Linux 20.04, GCC multilib (rumur single-threaded XML)
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - g++-multilib
          - libc6-dev-i386
          - libfl-dev
          - libxml2-utils
          - valgrind
    env:
      - TEST_ARGS="rumurOptimisedSingleThreadedXML rumurSingleThreadedXML"
      - MATRIX_EVAL="CC=gcc && CXX=g++"
      - CXXFLAGS="-pedantic -Werror -g -fno-omit-frame-pointer -fsanitize=undefined -fno-sanitize-recover=undefined -fuse-ld=gold"
      - UBSAN_OPTIONS=print_stacktrace=1

  - name: Ubuntu Linux 20.04, GCC multilib (rumur multithreaded XML)
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - g++-multilib
          - libc6-dev-i386
          - libfl-dev
          - libxml2-utils
          - valgrind
    env:
      - TEST_ARGS="rumurOptimisedMultithreadedXML rumurMultithreadedXML"
      - MATRIX_EVAL="CC=gcc && CXX=g++"
      - CXXFLAGS="-pedantic -Werror -g -fno-omit-frame-pointer -fsanitize=undefined -fno-sanitize-recover=undefined -fuse-ld=gold"
      - UBSAN_OPTIONS=print_stacktrace=1

  - name: Ubuntu Linux 20.04, GCC 10, AFL
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - g++-10
          - libfl-dev
    env:
      # install AFL and let it catch crashes via core dumps
      - MATRIX_EVAL="echo core | sudo tee /proc/sys/kernel/core_pattern && ./misc/install-afl.sh && CC=gcc-10 && CXX=afl-g++"

      # quit if we succeed exhaustively fuzzing (unlikely)
      - AFL_EXIT_WHEN_DONE=1

      # suppress normal animated UI and use periodic text output
      - AFL_NO_UI=1

      # enable ASan and UBSan
      - CXXFLAGS="-g -fsanitize=address,undefined -fno-sanitize-recover=undefined -O3"

      - CUSTOM_COMMAND="travis_wait 60 ../misc/afl-wrapper.sh"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - uname -sr && python3 --version && printf "_NPROCESSORS_ONLN " && getconf _NPROCESSORS_ONLN && mkdir build && cd build && cmake .. && cmake --build . -- -j2 && sudo env "PATH=$PATH" cmake --build . -- install && if [ -z "${CUSTOM_COMMAND}" ]; then env PATH=./rumur:./murphi2c:./murphi2murphi:./murphi2xml:./tests/murphi-comment-ls:${PATH} ../tests/run-tests.py --verbose ${TEST_ARGS}; else eval "${CUSTOM_COMMAND}"; fi
