language: cpp

branches:
  only:
    - master

matrix:
  include:


  - name: Ubuntu Linux 20.04, GCC 10, AFL
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - g++-10
          - libfl-dev
    env:
      # install AFL and let it catch crashes via core dumps
      - MATRIX_EVAL="echo core | sudo tee /proc/sys/kernel/core_pattern && ./misc/install-afl.sh && CC=gcc-10 && CXX=afl-g++"

      # quit if we succeed exhaustively fuzzing (unlikely)
      - AFL_EXIT_WHEN_DONE=1

      # suppress normal animated UI and use periodic text output
      - AFL_NO_UI=1

      # enable ASan and UBSan
      - CXXFLAGS="-g -fsanitize=address,undefined -fno-sanitize-recover=undefined -O3"

      - CUSTOM_COMMAND="travis_wait 60 ../misc/afl-wrapper.sh"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - uname -sr && python3 --version && printf "_NPROCESSORS_ONLN " && getconf _NPROCESSORS_ONLN && mkdir build && cd build && cmake .. && cmake --build . -- -j2 && sudo env "PATH=$PATH" cmake --build . -- install && if [ -z "${CUSTOM_COMMAND}" ]; then env PATH=./rumur:./murphi2c:./murphi2murphi:./murphi2xml:./tests/murphi-comment-ls:${PATH} ../tests/run-tests.py --verbose ${TEST_ARGS}; else eval "${CUSTOM_COMMAND}"; fi
