language: cpp

matrix:
  include:

  - name: Ubuntu Linux 20.04, GCC 7 (executable, murphi2c, murphi2xml)
    os: linux
    dist: focal
    addons:
      apt:
        packages:
          - g++-7
          - libfl-dev
          - libxml2-utils
          - z3
    env:
      - TEST_ARGS="executable murphi2c murphi2cHeader murphi2xml"
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      - CXXFLAGS="-pedantic -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold"
      - UBSAN_OPTIONS=print_stacktrace=1

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - uname -sr && python3 --version && mkdir build && cd build && cmake .. && cmake --build . -- -j$(getconf _NPROCESSORS_ONLN) && sudo env "PATH=$PATH" cmake --build . -- install && if [ -z "${CUSTOM_COMMAND}" ]; then env PATH=./rumur:./murphi2c:./murphi2murphi:./murphi2xml:./tests/murphi-comment-ls:${PATH} ../tests/run-tests.py --verbose ${TEST_ARGS}; else eval "${CUSTOM_COMMAND}"; fi
